Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2
      VpcId: <VPC_ID>
      SecurityGroupIngress:
        - CidrIp: <10.0.0.0>/24
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: <AMI_ID>
      SubnetId: <PRIVATE_SUBNET_ID>
      SecurityGroupIds:
        - !Ref MySecurityGroup
