Resources:
  maxiivanVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.2.0/24

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref maxiivanVPC
      CidrBlock: 192.168.2.1/26
      AvailabilityZone: us-east-1a

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref maxiivanVPC
      CidrBlock: 192.168.2.2/26
      AvailabilityZone: us-east-1b

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref maxiivanVPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref maxiivanVPC
