name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Deploy S3 Bucket
        run: |
          aws cloudformation create-stack --stack-name maxiivanS3Stack --template-body file://S3.yml
          aws cloudformation wait stack-create-complete --stack-name maxiivanS3Stack

      - name: Deploy VPC
        run: |
          aws cloudformation create-stack --stack-name maxiivanVPCStack --template-body file://VPC.yml
          aws cloudformation wait stack-create-complete --stack-name maxiivanVPCStack

      - name: Deploy EC2 Instance
        run: |
          aws cloudformation create-stack --stack-name maxiivanEC2Stack --template-body file://EC2.yml
          aws cloudformation wait stack-create-complete --stack-name maxiivanEC2Stack

